"""add_shipping_and_item_images

Revision ID: d3b6f71ddc64
Revises: 72b1d28d91eb
Create Date: 2026-03-25 00:20:42.534134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b6f71ddc64'
down_revision: Union[str, None] = '72b1d28d91eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('image_path', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('shipping_company', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('receipt_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'receipt_date')
    op.drop_column('orders', 'shipping_company')
    op.drop_column('order_items', 'image_path')
    # ### end Alembic commands ###
